# CI Pipeline - Build & Push Docker Image to GCP Artifact Registry

trigger:
- feature-branch   # triggers when you push to main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: azure-group
- name: IMAGE_TAG
  value: $(Build.BuildId)
- name: FULL_IMAGE
  value: '$(REGISTRY_URL)/$(PROJECT_ID)/$(REPO)/$(IMAGE_NAME):$(IMAGE_TAG)'

stages:
- stage: BuildAndPush
  jobs:
  - job: BuildPushJob
    steps:
    # ✅ Download GCP Key
    - task: DownloadSecureFile@1
      name: gcpKey
      inputs:
        secureFile: 'gcp-key.json'
    - task: Bash@3
      displayName: "Install gcloud CLI"
      inputs:
        targetType: 'inline'
        script: |
          echo "Installing Google Cloud SDK..."
          sudo apt-get update -y
          sudo apt-get install -y apt-transport-https ca-certificates gnupg curl
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update -y && sudo apt-get install -y google-cloud-cli

    # ✅ 3. Authenticate to GCP and Configure Docker
    - task: Bash@3
      displayName: "Authenticate to GCP and Configure Docker"
      inputs:
        targetType: 'inline'
        script: |
          echo "Activating GCP service account..."
          gcloud auth activate-service-account --key-file=$(gcpKey.secureFilePath)
          echo "Configuring Docker to use GCP Artifact Registry..."
          gcloud auth configure-docker $(REGISTRY_URL) -q

    # ✅ 4. Build Docker Image
    - task: Bash@3
      displayName: "Build Docker Image"
      inputs:
        targetType: 'inline'
        script: |
          echo "Building image: $(FULL_IMAGE)"
          docker build -t $(FULL_IMAGE) .

    # ✅ 5. Push Docker Image
    - task: Bash@3
      displayName: "Push Docker Image"
      inputs:
        targetType: 'inline'
        script: |
          echo "Pushing image: $(FULL_IMAGE)"
          docker push $(FULL_IMAGE)


    # - task: Bash@3
    #   displayName: "Trigger CD Pipeline"
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       echo "Triggering CD Pipeline..."
    #       az pipelines run --name "CD-Pipeline-Name" --parameters imageTag=$(Build.BuildId)
